apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/cluster-service: "true" 
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2.2.1
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE
          value: s3
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          value: AKIAXXXXXXXXXXXXXXXX 
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          value: yg3zvXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        - name: REGISTRY_STORAGE_S3_REGION
          value: aws-region-X
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: "your-bucket-name"
        - name: REGISTRY_STORAGE_S3_ENCRYPT
          value: "true"
        - name: REGISTRY_STORAGE_S3_SECURE
          value: "true"
        - name: REGISTRY_STORAGE_S3_V4AUTH
          value: "true"
        - name: REGISTRY_STORAGE_S3_CHUNKSIZE
          value: "5242880"
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
